#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: edxapp
  when: redeploy | default(False) | bool
- name: "Setup {{ COMMON_HOSTNAME }}"
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: edxapp
    nginx_sites:
     - lms
     - cms
     - verify
    nginx_default_sites:
     - lms
    NGINX_REDIRECT_TO_HTTPS: true
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp-common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/embargo.yaml"
  roles:
    - role: nginx
      tags: nginx
    - role: edxapp
      tags: edxapp
