#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: esforum
  when: redeploy | default(False) | bool
- name: "Setup {{ COMMON_HOSTNAME }}"
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: esforum
    ELASTICSEARCH_CLUSTER_NAME: "{{ COMMON_DEPLOYMENT }}-{{ CLUSTER_NAME }}"
    ELASTICSEARCH_HEAP_SIZE: "{{ (ansible_memtotal_mb / 2) | int }}m"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - common
    - oraclejdk
    - elasticsearch
