#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_ASSIGN_PUBLIC_IP: yes
    CLUSTER_INSTANCE_TAG_NAME: "{{ COMMON_DEPLOYMENT }}-box-{{ CLUSTER_NAME }}-{{ CLUSTER_SANDBOX_NAME }}"
    CLUSTER_INSTANCE_TYPE: t2.medium
    CLUSTER_NAME: sandbox
    CLUSTER_NETWORK: public
    CLUSTER_SANDBOX_NAME: master
  when: redeploy | default(False) | bool
# This is largely cribbed from `playbooks/roles/edx_sandbox.yml`
- name: Configure instance(s)
  hosts:
    - 'cluster_group_launched'
    - "tag_Name_{{ COMMON_DEPLOYMENT }}-box-sandbox-{{ CLUSTER_SANDBOX_NAME }}"
  become: True
  gather_facts: True
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  vars:
    migrate_db: "yes"
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    SANDBOX_ENABLE_ECOMMERCE: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 2GB
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: nginx
      nginx_sites:
      - ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: edxlocal
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - role: memcache
      when: "'localhost' in ' '.join(EDXAPP_MEMCACHE)"
    - role: mongo
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
    - role: edxapp
      celery_worker: True
    - edxapp
    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
      when: SANDBOX_ENABLE_ECOMMERCE
    - programs
    - analytics_api
    # broke: - insights
    # not ready yet: - edx_notes_api
    - demo
    - oauth_client_setup
    - oraclejdk
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
    - forum
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: 5
    - role: xqueue
      update_users: True
    # Temporarily disable certs installation
    # - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
