---
- name: Deploy the certificate agent
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
  vars_files:
    - "{{ secure_dir }}/vars/default/common.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/{{ env }}/certs.yml"
  roles:
    - role: certs
      tags: certs
