- hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ env }}/data-api.yml"
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir:  '{{ secure_dir }}/local'
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    COMMON_ENABLE_NEWRELIC: False
    COMMON_TAG_EC2_INSTANCE: False
  roles:
    - common
    - role: nginx
      nginx_sites:
        - analytics_api
    - role: analytics_api
      tags: analytics_api
