- name: Deploy Analytics Insights
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ env }}/insights.yml"
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    local_dir: '../../../configuration-secure/ansible/local'
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    COMMON_ENABLE_NEWRELIC: False
  roles:
    - role: nginx
      nginx_sites:
        - insights
    - insights
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
