---
- hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir:  '../../configuration-secure/ansible/local'
  vars_files:
    - "{{ secure_dir }}/vars/default/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/default/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/default/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/default/platform/env.yaml"
    - "{{ secure_dir }}/vars/default/platform/auth.yaml"
    - "{{ secure_dir }}/vars/default/lms/features.yaml"
    - "{{ secure_dir }}/vars/default/lms/microsites.yaml"
    - "{{ secure_dir }}/vars/default/lms/env.yaml"
    - "{{ secure_dir }}/vars/default/lms/auth.yaml"
    - "{{ secure_dir }}/vars/default/cms/env.yaml"
    - "{{ secure_dir }}/vars/default/cms/auth.yaml"

    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/lms/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/cms/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/{{ env }}/shib.yml"
  roles:
    - role: supervisor
      tags: supervisor
    - role: nginx
      nginx_sites:
        - maint
      nginx_default_sites:
        - maint
      tags: nginx
