---
- name: "Deploy notifier.{{ env }}"
  hosts: "~tag_Name_{{ machine }}_{{ env }}"
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/default/common.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/notifier.yml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
  roles:
    - role: notifier
      tags: notifier
